---
run:
  timeout: "120s"

output:
  format: "colored-line-number"

linters:
  enable:
    - gocyclo
    - unconvert
    - goimports
    - unused
    - vetshadow
    - misspell
    - nakedret
    - errcheck
    - revive
    - ineffassign
    - goconst
    - vet
    - unparam
    - gofumpt
    - prealloc
    - gomnd
    - gocritic


linters-settings:
  revive:
    rules:
      - name: package-comments
        disabled: true

issues:
  exclude-use-default: false
