name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: release
    runs-on: [ubuntu-latest]

    steps:
      - name: checkout the code
        uses: actions/checkout@v4

      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'

      - name: unshallow
        run: git fetch --prune --unshallow

      - name: run goreleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: "v2.8.1"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
