name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: test
    runs-on: [ubuntu-latest]

    steps:
      - name: checkout the code
        uses: actions/checkout@v4

      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'

      - name: unshallow
        run: git fetch --prune --unshallow

      - name: golanci-linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.7

      - name: configure
        run: make configure

      - name: build
        run: make build

      - name: run unit tests
        run: make test

      - name: run goreleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: "v2.8.1"
          args: check

      - name: upload code coverage
        uses: codecov/codecov-action@v5
        if: contains(github.ref, 'main')
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./cover.text
