name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: test
    runs-on: [ubuntu-latest]

    steps:
      - name: checkout the code
        uses: actions/checkout@v3

      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.x'

      - name: unshallow
        run: git fetch --prune --unshallow

      - name: golanci-linter
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.56.2

      - name: configure
        run: make configure

      - name: build
        run: make build

      - name: run unit tests
        run: make test

      - name: run goreleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: check

      - name: upload code coverage
        uses: codecov/codecov-action@v3.1.1
        if: contains(github.ref, 'main')
        with:
          file: ./cover.out
